version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: the-pixelmon-modpack
      CF_FILENAME_MATCHER: "9.1.2"
      MEMORY: 4G
    volumes:
      - mc-data:/data

volumes:
  mc-data: {}